"""ai resources schema

Revision ID: 79c1357c7aeb
Revises: c1178e6fb886
Create Date: 2026-08-04 21:14:29.099892

Table DDL below is autogenerated; the Row-Level Security block at the bottom
is hand-written -- RLS policies aren't part of SQLAlchemy's metadata, so
autogenerate can neither create nor diff them (docs/18-schema-rls-and-migrations.md).

Three RLS categories apply here, all following templates established in the
Phase 6 migration:

- **Standard tenant-owned** (`ai_assistants`, `assistant_members`,
  `knowledge_bases`, `documents`, `conversations`): `tenant_id = <context>`
  for both USING and WITH CHECK.
- **Nullable-tenant** (`model_configurations`): platform-default rows
  (`tenant_id IS NULL`) are readable by every tenant but writable by none,
  so SELECT is split from INSERT/UPDATE/DELETE -- one command per
  `CREATE POLICY`, since Postgres rejects `FOR INSERT, UPDATE, DELETE`.
- **Tenant-rows-only** (`provider_credentials`): docs/16 specifies "standard
  when `tenant_id` is set; platform-owned rows only accessible via the
  platform service layer" -- so unlike `model_configurations`, the
  `tenant_id IS NULL` rows here are *invisible* to `app_tenant` rather than
  shared. A tenant admin manages their own tenant's credentials on the
  ordinary tenant connection; platform-owned provider secrets never appear
  on it at all.

  Note what RLS does and does not buy here: it stops tenant A reading tenant
  B's ciphertext, but the ciphertext of one's *own* tenant is reachable on
  the tenant connection by design (that's how rotation works). The secret
  itself stays protected because the data key lives outside the database and
  because `ProviderCredentialSummary` -- the only shape any read use case
  returns -- has no field capable of carrying ciphertext.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79c1357c7aeb'
down_revision: Union[str, None] = 'c1178e6fb886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('provider_credential_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_budget_per_month', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_model_configurations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configurations')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_model_configurations_tenant_id_id')
    )
    op.create_table('provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('credential_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_hint', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(owner_type = 'platform' AND tenant_id IS NULL) OR (owner_type = 'tenant' AND tenant_id IS NOT NULL)", name=op.f('ck_provider_credentials_tenant_consistency')),
    sa.CheckConstraint("owner_type IN ('platform','tenant')", name=op.f('ck_provider_credentials_owner_type_valid')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_provider_credentials_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_provider_credentials_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_provider_credentials_tenant_id_id')
    )
    op.create_index('ix_provider_credentials_tenant_id', 'provider_credentials', ['tenant_id'], unique=False)
    op.create_table('ai_assistants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('owner_membership_id', sa.UUID(), nullable=False),
    sa.Column('model_configuration_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(visibility <> 'department' OR department_id IS NOT NULL) AND (visibility <> 'team' OR team_id IS NOT NULL)", name=op.f('ck_ai_assistants_visibility_scope_consistency')),
    sa.CheckConstraint("status IN ('draft','published','archived')", name=op.f('ck_ai_assistants_status_valid')),
    sa.CheckConstraint("visibility IN ('tenant','department','team','restricted')", name=op.f('ck_ai_assistants_visibility_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'model_configuration_id'], ['model_configurations.tenant_id', 'model_configurations.id'], name='fk_ai_assistants_model_configuration'),
    sa.ForeignKeyConstraint(['tenant_id', 'owner_membership_id'], ['tenant_memberships.tenant_id', 'tenant_memberships.id'], name='fk_ai_assistants_owner_membership'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ai_assistants_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_assistants')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_ai_assistants_tenant_id_id')
    )
    op.create_index('ix_ai_assistants_tenant_id', 'ai_assistants', ['tenant_id'], unique=False)
    op.create_index('ix_ai_assistants_tenant_status', 'ai_assistants', ['tenant_id', 'status'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_membership_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('vector_namespace', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(visibility <> 'department' OR department_id IS NOT NULL) AND (visibility <> 'team' OR team_id IS NOT NULL)", name=op.f('ck_knowledge_bases_visibility_scope_consistency')),
    sa.CheckConstraint("visibility IN ('tenant','department','team','restricted')", name=op.f('ck_knowledge_bases_visibility_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'owner_membership_id'], ['tenant_memberships.tenant_id', 'tenant_memberships.id'], name='fk_knowledge_bases_owner_membership'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_knowledge_bases_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_bases')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_knowledge_bases_tenant_id_id'),
    sa.UniqueConstraint('vector_namespace', name='uq_knowledge_bases_vector_namespace')
    )
    op.create_index('ix_knowledge_bases_tenant_id', 'knowledge_bases', ['tenant_id'], unique=False)
    op.create_table('assistant_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.Text(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("access_level IN ('viewer','editor','owner')", name=op.f('ck_assistant_members_access_level_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'assistant_id'], ['ai_assistants.tenant_id', 'ai_assistants.id'], name='fk_assistant_members_assistant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['tenant_memberships.tenant_id', 'tenant_memberships.id'], name='fk_assistant_members_membership', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_members')),
    sa.UniqueConstraint('assistant_id', 'membership_id', name='uq_assistant_members_pair')
    )
    op.create_index('ix_assistant_members_membership_id', 'assistant_members', ['membership_id'], unique=False)
    op.create_index('ix_assistant_members_tenant_id', 'assistant_members', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name=op.f('ck_conversations_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'assistant_id'], ['ai_assistants.tenant_id', 'ai_assistants.id'], name='fk_conversations_assistant'),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['tenant_memberships.tenant_id', 'tenant_memberships.id'], name='fk_conversations_membership'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_tenant_membership', 'conversations', ['tenant_id', 'membership_id', sa.literal_column('last_message_at DESC')], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('processing','ready','failed')", name=op.f('ck_documents_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'knowledge_base_id'], ['knowledge_bases.tenant_id', 'knowledge_bases.id'], name='fk_documents_knowledge_base'),
    sa.ForeignKeyConstraint(['tenant_id', 'uploaded_by_membership_id'], ['tenant_memberships.tenant_id', 'tenant_memberships.id'], name='fk_documents_uploaded_by_membership'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_knowledge_base_id', 'documents', ['knowledge_base_id'], unique=False)
    op.create_index('ix_documents_tenant_id', 'documents', ['tenant_id'], unique=False)
    op.create_index('uq_documents_storage_path_live', 'documents', ['storage_path'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###

    _apply_row_level_security()


# NULLIF(..., '') rather than a bare cast: a pooled connection that had
# app.tenant_id set in an earlier transaction reports '' (not NULL) in a later
# one that never re-set it, and `''::uuid` raises rather than evaluating to
# "no context, deny". Verified empirically in Phase 6 -- see
# docs/18-schema-rls-and-migrations.md and tests/integration/db/test_rls_isolation.py.
_TENANT_ID_EXPR = "NULLIF(current_setting('app.tenant_id', true), '')::uuid"

_STANDARD_TENANT_TABLES = (
    "ai_assistants",
    "assistant_members",
    "knowledge_bases",
    "documents",
    "conversations",
)


def _apply_row_level_security() -> None:
    for table in _STANDARD_TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_isolation ON {table} "
            f"USING (tenant_id = {_TENANT_ID_EXPR}) "
            f"WITH CHECK (tenant_id = {_TENANT_ID_EXPR})"
        )

    # model_configurations: platform defaults (tenant_id IS NULL) readable by
    # every tenant, writable by none. Separate policy per command -- Postgres
    # rejects `FOR INSERT, UPDATE, DELETE` in a single CREATE POLICY.
    op.execute("ALTER TABLE model_configurations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE model_configurations FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY model_configurations_read ON model_configurations "
        f"FOR SELECT USING (tenant_id IS NULL OR tenant_id = {_TENANT_ID_EXPR})"
    )
    op.execute(
        "CREATE POLICY model_configurations_insert ON model_configurations "
        f"FOR INSERT WITH CHECK (tenant_id = {_TENANT_ID_EXPR})"
    )
    op.execute(
        "CREATE POLICY model_configurations_update ON model_configurations "
        f"FOR UPDATE USING (tenant_id = {_TENANT_ID_EXPR}) "
        f"WITH CHECK (tenant_id = {_TENANT_ID_EXPR})"
    )
    op.execute(
        "CREATE POLICY model_configurations_delete ON model_configurations "
        f"FOR DELETE USING (tenant_id = {_TENANT_ID_EXPR})"
    )

    # provider_credentials: tenant-owned rows only -- platform-owned rows
    # (tenant_id IS NULL) are invisible to app_tenant, per docs/16.
    op.execute("ALTER TABLE provider_credentials ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE provider_credentials FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY provider_credentials_isolation ON provider_credentials "
        f"USING (tenant_id = {_TENANT_ID_EXPR}) "
        f"WITH CHECK (tenant_id = {_TENANT_ID_EXPR})"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_documents_storage_path_live', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_documents_tenant_id', table_name='documents')
    op.drop_index('ix_documents_knowledge_base_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_tenant_membership', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_assistant_members_tenant_id', table_name='assistant_members')
    op.drop_index('ix_assistant_members_membership_id', table_name='assistant_members')
    op.drop_table('assistant_members')
    op.drop_index('ix_knowledge_bases_tenant_id', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('ix_ai_assistants_tenant_status', table_name='ai_assistants')
    op.drop_index('ix_ai_assistants_tenant_id', table_name='ai_assistants')
    op.drop_table('ai_assistants')
    op.drop_index('ix_provider_credentials_tenant_id', table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_table('model_configurations')
    # ### end Alembic commands ###
