"""platform tenancy and tenant authorization schema

Revision ID: c1178e6fb886
Revises: 733709e886a7
Create Date: 2026-08-03 21:08:58.186033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1178e6fb886'
down_revision: Union[str, None] = '733709e886a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("risk_level IN ('low','medium','high','critical')", name=op.f('ck_platform_permissions_risk_level_valid')),
    sa.CheckConstraint("scope = 'platform'", name=op.f('ck_platform_permissions_scope_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_platform_permissions_code'))
    )
    op.create_table('platform_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_platform_roles_code'))
    )
    op.create_table('role_hierarchy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_role_id', sa.UUID(), nullable=False),
    sa.Column('child_role_id', sa.UUID(), nullable=False),
    sa.Column('role_scope', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("role_scope IN ('platform','tenant')", name=op.f('ck_role_hierarchy_role_scope_valid')),
    sa.CheckConstraint('parent_role_id <> child_role_id', name=op.f('ck_role_hierarchy_no_self_loop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_hierarchy')),
    sa.UniqueConstraint('parent_role_id', 'child_role_id', name='uq_role_hierarchy_edge')
    )
    op.create_table('tenant_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('tenant_customizable', sa.Boolean(), nullable=False),
    sa.Column('required_feature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("risk_level IN ('low','medium','high','critical')", name=op.f('ck_tenant_permissions_risk_level_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_permissions')),
    sa.UniqueConstraint('code', name='uq_tenant_permissions_code')
    )
    op.create_table('platform_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['platform_permissions.id'], name='fk_platform_role_permissions_permission_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['platform_roles.id'], name='fk_platform_role_permissions_role_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_platform_role_permissions'))
    )
    op.create_table('platform_user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_platform_user_roles_granted_by_user_id_users')),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], name=op.f('fk_platform_user_roles_revoked_by_user_id_users')),
    sa.ForeignKeyConstraint(['role_id'], ['platform_roles.id'], name=op.f('fk_platform_user_roles_role_id_platform_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_platform_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_user_roles'))
    )
    op.create_index('ix_platform_user_roles_user_id', 'platform_user_roles', ['user_id'], unique=False)
    op.create_index('uq_platform_user_roles_active', 'platform_user_roles', ['user_id', 'role_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','active','suspended','deactivated')", name=op.f('ck_tenants_status_valid')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_tenants_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_index('ix_tenants_status', 'tenants', ['status'], unique=False)
    op.create_table('authorization_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('platform_permission_id', sa.UUID(), nullable=True),
    sa.Column('tenant_permission_id', sa.UUID(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(scope = 'platform' AND tenant_id IS NULL AND subject_type = 'platform_user' AND platform_permission_id IS NOT NULL AND tenant_permission_id IS NULL) OR (scope = 'tenant' AND tenant_id IS NOT NULL AND subject_type = 'membership' AND tenant_permission_id IS NOT NULL AND platform_permission_id IS NULL)", name=op.f('ck_authorization_overrides_scope_consistency')),
    sa.CheckConstraint("effect IN ('allow','deny')", name=op.f('ck_authorization_overrides_effect_valid')),
    sa.CheckConstraint("scope IN ('platform','tenant')", name=op.f('ck_authorization_overrides_scope_valid')),
    sa.CheckConstraint("subject_type IN ('membership','platform_user')", name=op.f('ck_authorization_overrides_subject_type_valid')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_authorization_overrides_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['platform_permission_id'], ['platform_permissions.id'], name=op.f('fk_authorization_overrides_platform_permission_id_platform_permissions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_authorization_overrides_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_permission_id'], ['tenant_permissions.id'], name=op.f('fk_authorization_overrides_tenant_permission_id_tenant_permissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authorization_overrides'))
    )
    op.create_table('impersonation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_user_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approval_status', sa.Text(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("approval_status IN ('not_required','pending','approved','denied')", name=op.f('ck_impersonation_sessions_approval_status_valid')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_impersonation_sessions_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['platform_user_id'], ['users.id'], name=op.f('fk_impersonation_sessions_platform_user_id_users')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_impersonation_sessions_target_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_impersonation_sessions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impersonation_sessions'))
    )
    op.create_index('ix_impersonation_sessions_platform_user_id', 'impersonation_sessions', ['platform_user_id'], unique=False)
    op.create_index('ix_impersonation_sessions_target_user_id', 'impersonation_sessions', ['target_user_id'], unique=False)
    op.create_table('tenant_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('feature_code', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_tenant_features_granted_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_tenant_features_tenant_id_tenants', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_features')),
    sa.UniqueConstraint('tenant_id', 'feature_code', name='uq_tenant_features_tenant_id_feature_code')
    )
    op.create_table('tenant_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('role_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('pending','accepted','revoked','expired')", name=op.f('ck_tenant_invitations_status_valid')),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('fk_tenant_invitations_accepted_by_user_id_users')),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_tenant_invitations_invited_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_invitations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_invitations')),
    sa.UniqueConstraint('token_hash', name='uq_tenant_invitations_token_hash')
    )
    op.create_index('ix_tenant_invitations_tenant_id', 'tenant_invitations', ['tenant_id'], unique=False)
    op.create_index('ux_tenant_invitations_pending_per_email', 'tenant_invitations', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('tenant_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('invited','active','suspended','revoked')", name=op.f('ck_tenant_memberships_status_valid')),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_tenant_memberships_invited_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tenant_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_memberships')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_tenant_memberships_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_memberships_tenant_id_user_id')
    )
    op.create_index('ix_tenant_memberships_tenant_id', 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_memberships_tenant_status', 'tenant_memberships', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_tenant_memberships_user_id', 'tenant_memberships', ['user_id'], unique=False)
    op.create_index('ux_tenant_memberships_one_default_per_user', 'tenant_memberships', ['user_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('tenant_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(tenant_id IS NULL AND is_system) OR (tenant_id IS NOT NULL AND NOT is_system)', name=op.f('ck_tenant_roles_system_consistency')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_tenant_roles_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_roles')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_tenant_roles_tenant_id_id')
    )
    op.create_index('uq_tenant_roles_code', 'tenant_roles', [sa.literal_column("COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid)"), 'code'], unique=True)
    op.create_table('tenant_membership_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_tenant_membership_roles_granted_by_user_id_users')),
    sa.ForeignKeyConstraint(['role_id'], ['tenant_roles.id'], name='fk_tenant_membership_roles_role_id'),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['tenant_memberships.tenant_id', 'tenant_memberships.id'], name='fk_tenant_membership_roles_membership', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_membership_roles'))
    )
    op.create_index('ix_tenant_membership_roles_tenant_id', 'tenant_membership_roles', ['tenant_id'], unique=False)
    op.create_index('uq_tenant_membership_roles_active', 'tenant_membership_roles', ['membership_id', 'role_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('tenant_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['tenant_permissions.id'], name='fk_tenant_role_permissions_permission_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['tenant_roles.id'], name='fk_tenant_role_permissions_role_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_tenant_role_permissions'))
    )
    # ### end Alembic commands ###

    op.create_check_constraint(
        "platform_scope_has_no_tenant",
        "role_hierarchy",
        "(role_scope = 'platform' AND tenant_id IS NULL) OR role_scope = 'tenant'",
    )

    _apply_row_level_security()


# --- Row-Level Security -------------------------------------------------
#
# docs/18-schema-rls-and-migrations.md, corrected during Phase 6
# implementation: every read-side comparison uses
# NULLIF(current_setting(name, true), '')::uuid rather than a direct
# ::uuid cast, because a *reused pooled connection* that has ever had the
# setting assigned reverts to '' (empty string), not NULL, once the
# transaction that set it ends -- a direct cast raises
# `invalid input syntax for type uuid: ""` on that next transaction instead
# of cleanly evaluating to "no context, deny". Verified empirically against
# a live connection with pool_size=1 before writing this.

_PLATFORM_ONLY_TABLES = (
    "platform_permissions",
    "platform_roles",
    "platform_role_permissions",
    "platform_user_roles",
    "impersonation_sessions",
)

_STANDARD_TENANT_TABLES = (
    "authorization_overrides",
    "tenant_features",
    "tenant_invitations",
    "tenant_membership_roles",
)

_NULLABLE_TENANT_TABLES = (
    "tenant_roles",
    "tenant_role_permissions",
)

_TENANT_ID_EXPR = "NULLIF(current_setting('app.tenant_id', true), '')::uuid"


def _apply_row_level_security() -> None:
    # Platform-only tables: enable + force RLS with NO policy at all, which
    # is a default-deny for every role except the table owner's BYPASSRLS-
    # equivalent bypass -- only app_platform (BYPASSRLS) can see these rows.
    # The REVOKE is belt-and-suspenders on top of that (docs/18): app_tenant
    # would otherwise still hold the blanket CRUD grant every table gets via
    # `ALTER DEFAULT PRIVILEGES` in docker/postgres-init/01-roles.sql.
    for table in _PLATFORM_ONLY_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"REVOKE ALL ON {table} FROM app_tenant")

    # tenants: not tenant-owned (it IS the tenant), but must not be freely
    # readable/writable by app_tenant across tenant boundaries -- found
    # during Phase 6 implementation (a table autogenerate had no reason to
    # flag, since it isn't in the docs/11-18 "standard tenant-owned" list,
    # but leaving it ungated would let any authenticated tenant request read
    # or modify every OTHER tenant's row). Read-only, and only the active
    # tenant's own row.
    op.execute("ALTER TABLE tenants ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tenants FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenants_read ON tenants FOR SELECT USING (id = {_TENANT_ID_EXPR})"
    )
    op.execute("REVOKE INSERT, UPDATE, DELETE ON tenants FROM app_tenant")

    # Standard tenant-owned tables: the docs/18 template.
    for table in _STANDARD_TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_isolation ON {table} "
            f"USING (tenant_id = {_TENANT_ID_EXPR}) "
            f"WITH CHECK (tenant_id = {_TENANT_ID_EXPR})"
        )

    # tenant_memberships: standard template PLUS the self-lookup read
    # exception that makes "which tenants am I a member of" resolvable
    # before any tenant_id is active (docs/07-tenant-isolation-and-rls.md §2,
    # application/tenancy/list_memberships.py).
    op.execute("ALTER TABLE tenant_memberships ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tenant_memberships FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_memberships_isolation ON tenant_memberships "
        f"USING (tenant_id = {_TENANT_ID_EXPR} OR user_id = "
        "NULLIF(current_setting('app.user_id', true), '')::uuid) "
        f"WITH CHECK (tenant_id = {_TENANT_ID_EXPR})"
    )

    # Nullable-tenant tables (tenant_roles, tenant_role_permissions): system
    # rows (tenant_id IS NULL) are readable tenant-wide but writable by no
    # tenant -- split SELECT from INSERT/UPDATE/DELETE. PostgreSQL's
    # CREATE POLICY only accepts a single command per policy (`FOR INSERT,
    # UPDATE, DELETE` in one statement is a syntax error, caught by actually
    # running this migration against Postgres rather than just reading the
    # SQL) -- three separate policies instead of one comma-separated FOR.
    for table in _NULLABLE_TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_read ON {table} "
            f"FOR SELECT USING (tenant_id IS NULL OR tenant_id = {_TENANT_ID_EXPR})"
        )
        op.execute(
            f"CREATE POLICY {table}_insert ON {table} "
            f"FOR INSERT WITH CHECK (tenant_id = {_TENANT_ID_EXPR})"
        )
        op.execute(
            f"CREATE POLICY {table}_update ON {table} "
            f"FOR UPDATE USING (tenant_id = {_TENANT_ID_EXPR}) "
            f"WITH CHECK (tenant_id = {_TENANT_ID_EXPR})"
        )
        op.execute(
            f"CREATE POLICY {table}_delete ON {table} "
            f"FOR DELETE USING (tenant_id = {_TENANT_ID_EXPR})"
        )

    # role_hierarchy: mixed platform-scope and tenant-scope rows in one
    # table, distinguished by role_scope -- tenant_id alone is ambiguous
    # (both a platform edge and a tenant *system*-role edge have tenant_id
    # NULL), so every clause is role_scope-qualified. Platform-scope rows
    # fall through with no matching policy => invisible to app_tenant,
    # exactly like the platform-only tables above.
    op.execute("ALTER TABLE role_hierarchy ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE role_hierarchy FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY role_hierarchy_read ON role_hierarchy "
        "FOR SELECT USING ("
        f"role_scope = 'tenant' AND (tenant_id IS NULL OR tenant_id = {_TENANT_ID_EXPR})"
        ")"
    )
    op.execute(
        "CREATE POLICY role_hierarchy_insert ON role_hierarchy "
        "FOR INSERT WITH CHECK "
        f"(role_scope = 'tenant' AND tenant_id = {_TENANT_ID_EXPR})"
    )
    op.execute(
        "CREATE POLICY role_hierarchy_update ON role_hierarchy "
        f"FOR UPDATE USING (role_scope = 'tenant' AND tenant_id = {_TENANT_ID_EXPR}) "
        f"WITH CHECK (role_scope = 'tenant' AND tenant_id = {_TENANT_ID_EXPR})"
    )
    op.execute(
        "CREATE POLICY role_hierarchy_delete ON role_hierarchy "
        f"FOR DELETE USING (role_scope = 'tenant' AND tenant_id = {_TENANT_ID_EXPR})"
    )

    # tenant_permissions: a global, not-tenant-owned catalog (like
    # platform_permissions) -- readable by app_tenant (every tenant needs to
    # resolve permission codes), no RLS needed since there's no tenant_id to
    # scope by. Write access is deliberately NOT locked down to a
    # migration-only role in this phase (a real hardening pass would REVOKE
    # INSERT/UPDATE/DELETE from app_tenant here too, matching tenants'
    # write lockout above) -- noted as deferred rather than silently skipped.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_role_permissions')
    op.drop_index('uq_tenant_membership_roles_active', table_name='tenant_membership_roles', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_tenant_membership_roles_tenant_id', table_name='tenant_membership_roles')
    op.drop_table('tenant_membership_roles')
    op.drop_index('uq_tenant_roles_code', table_name='tenant_roles')
    op.drop_table('tenant_roles')
    op.drop_index('ux_tenant_memberships_one_default_per_user', table_name='tenant_memberships', postgresql_where=sa.text('is_default'))
    op.drop_index('ix_tenant_memberships_user_id', table_name='tenant_memberships')
    op.drop_index('ix_tenant_memberships_tenant_status', table_name='tenant_memberships')
    op.drop_index('ix_tenant_memberships_tenant_id', table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index('ux_tenant_invitations_pending_per_email', table_name='tenant_invitations', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_tenant_invitations_tenant_id', table_name='tenant_invitations')
    op.drop_table('tenant_invitations')
    op.drop_table('tenant_features')
    op.drop_index('ix_impersonation_sessions_target_user_id', table_name='impersonation_sessions')
    op.drop_index('ix_impersonation_sessions_platform_user_id', table_name='impersonation_sessions')
    op.drop_table('impersonation_sessions')
    op.drop_table('authorization_overrides')
    op.drop_index('ix_tenants_status', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('uq_platform_user_roles_active', table_name='platform_user_roles', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_platform_user_roles_user_id', table_name='platform_user_roles')
    op.drop_table('platform_user_roles')
    op.drop_table('platform_role_permissions')
    op.drop_table('tenant_permissions')
    op.drop_table('role_hierarchy')
    op.drop_table('platform_roles')
    op.drop_table('platform_permissions')
    # ### end Alembic commands ###
