"""The PDF fast path, and the thing that makes it safe: knowing when to decline.

A fast parser that silently mangles scanned documents would be worse than no
fast parser at all -- the tenant would get a `ready` document containing
nothing, which looks like a working upload and answers no questions. So the
decline path gets more tests here than the happy path.
"""

from __future__ import annotations

import pytest

from iam_platform.application.ai_resources.exceptions import (
    DocumentParseError,
    UnsupportedDocumentTypeError,
)
from iam_platform.application.ai_resources.ports import ParsedBlock
from iam_platform.core.config import IngestionSettings
from iam_platform.infrastructure.parsing.dispatcher import ParserDispatcher
from iam_platform.infrastructure.parsing.fast_pdf import FastPdfParser, ParserDeclined

pytestmark = pytest.mark.unit


def _pdf(pages: list[str]) -> bytes:
    """A minimal, valid PDF carrying a real text layer.

    Hand-built rather than generated by a library so the test does not depend
    on the very machinery it is testing.
    """
    objects: list[bytes] = []
    kids = " ".join(f"{4 + i * 2} 0 R" for i in range(len(pages)))
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(
        f"<< /Type /Pages /Count {len(pages)} /Kids [{kids}] >>".encode()
    )
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    for text in pages:
        escaped = text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
        stream = f"BT /F1 12 Tf 72 720 Td ({escaped}) Tj ET".encode()
        objects.append(
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 3 0 R >> >> /Contents "
            + str(len(objects) + 2).encode()
            + b" 0 R >>"
        )
        objects.append(
            b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n"
            + stream + b"\nendstream"
        )

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode() + body + b"\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode() + b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n".encode()
        + b"%%EOF\n"
    )
    return bytes(out)


class TestTextNativePdfs:
    async def test_extracts_the_text_layer(self) -> None:
        data = _pdf(["Refunds are issued within fourteen days of receipt."])

        blocks = await FastPdfParser().parse(
            data=data, content_type="application/pdf", filename="policy.pdf"
        )

        assert "fourteen days" in " ".join(b.text for b in blocks)

    async def test_citations_name_the_page(self) -> None:
        """The reason this path improves citations rather than only speed:
        page numbers come free from the text layer, where docling reports them
        inconsistently and falls back to headings."""
        # Both strings are deliberately past `pdf_min_chars_per_page` (50).
        # The first draft of this test used 46- and 43-character pages and
        # failed by declining -- which is the guard working correctly.
        data = _pdf(["First page content here, comfortably long enough to count as text.",
                     "Second page content here, also comfortably long enough to count."])

        blocks = await FastPdfParser().parse(
            data=data, content_type="application/pdf", filename="two.pdf"
        )

        locations = {b.source_location for b in blocks}
        assert locations == {"page 1", "page 2"}

    async def test_a_block_never_spans_two_pages(self) -> None:
        data = _pdf(["Alpha content that is long enough to count as text.",
                     "Beta content that is long enough to count as text."])

        blocks = await FastPdfParser().parse(
            data=data, content_type="application/pdf", filename="two.pdf"
        )

        for block in blocks:
            assert not ("Alpha" in block.text and "Beta" in block.text)


class TestDeclining:
    async def test_a_pdf_with_no_text_layer_is_declined(self) -> None:
        """The scanned-document case. Declining hands it to docling's OCR;
        *not* declining would produce an empty document that looks ingested."""
        data = _pdf(["", ""])

        with pytest.raises(ParserDeclined):
            await FastPdfParser().parse(
                data=data, content_type="application/pdf", filename="scan.pdf"
            )

    async def test_a_mostly_scanned_pdf_is_declined(self) -> None:
        """One text page out of four is below the 0.6 ratio: the document is
        substantially images, so the whole thing goes to OCR rather than
        silently losing three pages."""
        data = _pdf(["A page with plenty of real text on it, easily past the threshold.",
                     "", "", ""])

        with pytest.raises(ParserDeclined):
            await FastPdfParser().parse(
                data=data, content_type="application/pdf", filename="mostly-scan.pdf"
            )

    async def test_one_image_page_does_not_condemn_a_text_document(self) -> None:
        """The opposite error, and the reason the ratio is not 1.0: real
        reports contain full-page diagrams, and one should not push a whole
        document through OCR."""
        data = _pdf(["Text page one, comfortably above the character threshold.",
                     "Text page two, comfortably above the character threshold.",
                     "Text page three, comfortably above the threshold too.",
                     ""])

        blocks = await FastPdfParser().parse(
            data=data, content_type="application/pdf", filename="one-diagram.pdf"
        )

        assert blocks

    async def test_the_fast_path_can_be_switched_off(self) -> None:
        settings = IngestionSettings(pdf_text_layer_first=False)

        with pytest.raises(ParserDeclined):
            await FastPdfParser(settings).parse(
                data=_pdf(["Plenty of text on this page for the threshold."]),
                content_type="application/pdf",
                filename="policy.pdf",
            )

    async def test_a_corrupt_pdf_fails_rather_than_declining(self) -> None:
        """Declining would send a broken file to docling, which also cannot
        read it -- the tenant would then get docling's error instead of the
        real one, and two parsers' time would be spent to reach the same
        conclusion."""
        with pytest.raises(DocumentParseError):
            await FastPdfParser().parse(
                data=b"this is not a pdf at all",
                content_type="application/pdf",
                filename="broken.pdf",
            )


class _Recording:
    """Stands in for docling so the dispatcher's fallthrough can be observed
    without loading several hundred megabytes of ML models."""

    def __init__(self) -> None:
        self.called = False

    def supports(self, *, content_type: str, filename: str) -> bool:
        del content_type
        return filename.lower().endswith(".pdf")

    async def parse(self, *, data: bytes, content_type: str, filename: str) -> list[ParsedBlock]:
        del data, content_type, filename
        self.called = True
        return [ParsedBlock(text="ocr output", source_location=None)]


class TestDispatcherFallthrough:
    async def test_a_decline_falls_through_to_the_next_parser(self) -> None:
        docling = _Recording()
        dispatcher = ParserDispatcher([FastPdfParser(), docling])  # type: ignore[list-item]

        blocks = await dispatcher.parse(
            data=_pdf(["", ""]), content_type="application/pdf", filename="scan.pdf"
        )

        assert docling.called
        assert blocks[0].text == "ocr output"

    async def test_a_text_pdf_never_reaches_docling(self) -> None:
        """The whole point: the expensive parser must not run when the cheap
        one succeeded. Measured at ~11ms versus ~15s on a one-page file."""
        docling = _Recording()
        dispatcher = ParserDispatcher([FastPdfParser(), docling])  # type: ignore[list-item]

        await dispatcher.parse(
            data=_pdf(["Real text, comfortably above the threshold for a page."]),
            content_type="application/pdf",
            filename="policy.pdf",
        )

        assert not docling.called

    async def test_a_broken_file_is_not_retried_by_the_next_parser(self) -> None:
        docling = _Recording()
        dispatcher = ParserDispatcher([FastPdfParser(), docling])  # type: ignore[list-item]

        with pytest.raises(DocumentParseError):
            await dispatcher.parse(
                data=b"not a pdf", content_type="application/pdf", filename="broken.pdf"
            )

        assert not docling.called

    async def test_an_unclaimed_format_still_raises(self) -> None:
        dispatcher = ParserDispatcher([FastPdfParser()])

        with pytest.raises(UnsupportedDocumentTypeError):
            await dispatcher.parse(
                data=b"x", content_type="application/zip", filename="archive.zip"
            )
